export const DESIGNATION_DATA = [
  {
    id: 1,
    title: "Accountant",
    department: "Finance",
    employees: 10,
    status: "Active",
    createdDate: "Jan 5 2026",
  },
  {
    id: 2,
    title: "App Developer",
    department: "Engineering",
    employees: 15,
    status: "Active",
    createdDate: "Jul 5 2026",
  },
  {
    id: 3,
    title: "Technician",
    department: "IT Infrastructure",
    employees: 8,
    status: "Active",
    createdDate: "Feb 3 2026",
  },
  {
    id: 4,
    title: "Web Developer",
    department: "Engineering",
    employees: 10,
    status: "Active",
    createdDate: "Feb 18 2026",
  },
  {
    id: 5,
    title: "Sales Executive Officer",
    department: "Sales",
    employees: 10,
    status: "Active",
    createdDate: "Mar 7 2026",
  },
  {
    id: 6,
    title: "Designer",
    department: "Design",
    employees: 15,
    status: "Active",
    createdDate: "Mar 22 2025",
  },
  {
    id: 7,
    title: "HR Manager",
    department: "HR",
    employees: 5,
    status: "Active",
    createdDate: "Apr 1 2025",
  },
  {
    id: 8,
    title: "Marketing Analyst",
    department: "Marketing",
    employees: 12,
    status: "Active",
    createdDate: "Apr 15 2026",
  },
  {
    id: 9,
    title: "Product Manager",
    department: "Product",
    employees: 6,
    status: "Active",
    createdDate: "Apr 28 2026",
  },
  {
    id: 10,
    title: "QA Engineer",
    department: "Quality Assurance",
    employees: 9,
    status: "Inactive",
    createdDate: "May 6 2026",
  },
  {
    id: 11,
    title: "DevOps Engineer",
    department: "IT Infrastructure",
    employees: 7,
    status: "Active",
    createdDate: "May 12 2026",
  },
  {
    id: 12,
    title: "Legal Counsel",
    department: "Legal",
    employees: 4,
    status: "Active",
    createdDate: "May 19 2026",
  },
  {
    id: 13,
    title: "Operations Manager",
    department: "Operations",
    employees: 8,
    status: "Active",
    createdDate: "Jun 2 2026",
  },
  {
    id: 14,
    title: "Procurement Officer",
    department: "Procurement",
    employees: 5,
    status: "Inactive",
    createdDate: "Jun 5 2026",
  },
  {
    id: 15,
    title: "R&D Scientist",
    department: "Research & Development",
    employees: 11,
    status: "Active",
    createdDate: "Jun 8 2026",
  },
  {
    id: 16,
    title: "Support Agent",
    department: "Customer Support",
    employees: 20,
    status: "Active",
    createdDate: "Jun 10 2026",
  },
  {
    id: 17,
    title: "Finance Analyst",
    department: "Finance",
    employees: 8,
    status: "Active",
    createdDate: "Jun 12 2026",
  },
  {
    id: 18,
    title: "UI/UX Designer",
    department: "Design",
    employees: 6,
    status: "Active",
    createdDate: "Jun 14 2026",
  },
  {
    id: 19,
    title: "Backend Developer",
    department: "Engineering",
    employees: 14,
    status: "Active",
    createdDate: "Jun 16 2026",
  },
  {
    id: 20,
    title: "Admin Executive",
    department: "Administration",
    employees: 4,
    status: "Inactive",
    createdDate: "Jun 17 2026",
  },
];

export const DESIGNATION_DEPARTMENTS = [
  "Finance",
  "Engineering",
  "IT Infrastructure",
  "Sales",
  "Design",
  "HR",
  "Marketing",
  "Product",
  "Quality Assurance",
  "Legal",
  "Operations",
  "Procurement",
  "Research & Development",
  "Customer Support",
  "Administration",
];
