// ── Employee List Static Data ──────────────────────────────────

export const EMPLOYEE_DATA = [
  {
    id: 1,
    empId: "Emp-001",
    name: "Anthony Lewis",
    avatar: "AL",
    color: "bg-blue-500",
    department: "Finance",
    designation: "Finance",
    email: "anthony@example.com",
    phone: "(123) 4567 890",
    joiningDate: "12 Sep 2024",
    status: "Active",
    projects: 20,
    done: 13,
    progress: 7,
    productivity: 65,
  },
  {
    id: 2,
    empId: "Emp-002",
    name: "Brian Villalobos",
    avatar: "BV",
    color: "bg-teal-500",
    department: "Engineering",
    designation: "Developer",
    email: "brian@example.com",
    phone: "(179) 7382 829",
    joiningDate: "24 Oct 2024",
    status: "Active",
    projects: 30,
    done: 10,
    progress: 20,
    productivity: 30,
  },
  {
    id: 3,
    empId: "Emp-003",
    name: "Harvey Smith",
    avatar: "HS",
    color: "bg-amber-500",
    department: "Engineering",
    designation: "Developer",
    email: "harvey@example.com",
    phone: "(184) 2719 738",
    joiningDate: "18 Feb 2024",
    status: "Active",
    projects: 25,
    done: 7,
    progress: 18,
    productivity: 20,
  },
  {
    id: 4,
    empId: "Emp-004",
    name: "Stephan Peralt",
    avatar: "SP",
    color: "bg-purple-500",
    department: "Management",
    designation: "Executive",
    email: "peral@example.com",
    phone: "(193) 7839 748",
    joiningDate: "17 Oct 2024",
    status: "Active",
    projects: 15,
    done: 13,
    progress: 2,
    productivity: 90,
  },
  {
    id: 5,
    empId: "Emp-005",
    name: "Doglas Martini",
    avatar: "DM",
    color: "bg-pink-500",
    department: "Development",
    designation: "Manager",
    email: "martniwr@example.com",
    phone: "(183) 9302 890",
    joiningDate: "20 Jul 2024",
    status: "Active",
    projects: 15,
    done: 2,
    progress: 13,
    productivity: 10,
  },
  {
    id: 6,
    empId: "Emp-006",
    name: "Linda Ray",
    avatar: "LR",
    color: "bg-indigo-400",
    department: "Finance",
    designation: "Finance",
    email: "ray456@example.com",
    phone: "(120) 3728 039",
    joiningDate: "10 Apr 2024",
    status: "Active",
    projects: 20,
    done: 10,
    progress: 10,
    productivity: 50,
  },
  {
    id: 7,
    empId: "Emp-007",
    name: "Elliot Murray",
    avatar: "EM",
    color: "bg-green-500",
    department: "Finance",
    designation: "Developer",
    email: "murray@example.com",
    phone: "(102) 8480 832",
    joiningDate: "29 Aug 2024",
    status: "Active",
    projects: 40,
    done: 35,
    progress: 5,
    productivity: 93,
  },
  {
    id: 8,
    empId: "Emp-008",
    name: "Rebecca Smith",
    avatar: "RS",
    color: "bg-rose-400",
    department: "QA",
    designation: "Executive",
    email: "smtih@example.com",
    phone: "(162) 8920 713",
    joiningDate: "22 Feb 2024",
    status: "Inactive",
    projects: 30,
    done: 22,
    progress: 8,
    productivity: 80,
  },
  {
    id: 9,
    empId: "Emp-009",
    name: "Connie Waters",
    avatar: "CW",
    color: "bg-cyan-500",
    department: "Admin",
    designation: "Manager",
    email: "connie@example.com",
    phone: "(145) 6732 099",
    joiningDate: "03 Mar 2024",
    status: "Active",
    projects: 12,
    done: 8,
    progress: 4,
    productivity: 72,
  },
  {
    id: 10,
    empId: "Emp-010",
    name: "Lori Broaddus",
    avatar: "LB",
    color: "bg-yellow-500",
    department: "Analytics",
    designation: "Manager",
    email: "lori@example.com",
    phone: "(177) 4521 663",
    joiningDate: "15 Jan 2024",
    status: "Inactive",
    projects: 18,
    done: 14,
    progress: 4,
    productivity: 45,
  },
];

export const DESIGNATIONS = [
  "All Designations",
  "Finance",
  "Developer",
  "Executive",
  "Manager",
];

export const STATUSES = ["All Status", "Active", "Inactive"];

export const SORT_OPTIONS = [
  "Recently Added",
  "Ascending",
  "Descending",
  "Last 7 Days",
  "Last Month",
];

export const ROWS_OPTIONS = [10, 25, 50, 100];

export const PRODUCTIVITY_COLORS = [
  { max: 25, bar: "#ef4444", text: "text-red-500" },
  { max: 50, bar: "#f59e0b", text: "text-amber-500" },
  { max: 75, bar: "#a855f7", text: "text-purple-500" },
  { max: 100, bar: "#22c55e", text: "text-green-500" },
];

export const getProductivityStyle = (pct) =>
  PRODUCTIVITY_COLORS.find((c) => pct <= c.max) || PRODUCTIVITY_COLORS[3];
