const allUsers = [
  {
    id: 1,
    name: "Anthony Lewis",
    email: "anthony@example.com",
    date: "05 Jan 2026",
    role: "Employee",
    status: "Active",
    avatar: "https://i.pravatar.cc/40?img=1",
  },
  {
    id: 2,
    name: "Brian Villalobos",
    email: "brian@example.com",
    date: "12 Jan 2026",
    role: "Employee",
    status: "Active",
    avatar: "https://i.pravatar.cc/40?img=2",
  },
  {
    id: 3,
    name: "Sophie Headrick",
    email: "sophie@example.com",
    date: "20 Jan 2026",
    role: "Client",
    status: "Active",
    avatar: "https://i.pravatar.cc/40?img=3",
  },
  {
    id: 4,
    name: "Stephan Peralt",
    email: "peral@example.com",
    date: "02 Feb 2026",
    role: "Employee",
    status: "Active",
    avatar: "https://i.pravatar.cc/40?img=4",
  },
  {
    id: 5,
    name: "Thomas Bordelon",
    email: "thomas@example.com",
    date: "10 Feb 2026",
    role: "Client",
    status: "Active",
    avatar: "https://i.pravatar.cc/40?img=5",
  },
  {
    id: 6,
    name: "Doglas Martini",
    email: "martinwr@example.com",
    date: "18 Feb 2026",
    role: "Employee",
    status: "Active",
    avatar: "https://i.pravatar.cc/40?img=6",
  },
  {
    id: 7,
    name: "Cameron Drake",
    email: "cameron@example.com",
    date: "25 Feb 2026",
    role: "Client",
    status: "Active",
    avatar: "https://i.pravatar.cc/40?img=7",
  },
  {
    id: 8,
    name: "Harvey Smith",
    email: "harvey@example.com",
    date: "05 Mar 2026",
    role: "Employee",
    status: "Inactive",
    avatar: "https://i.pravatar.cc/40?img=8",
  },
  {
    id: 9,
    name: "Michael Walker",
    email: "michael@example.com",
    date: "12 Mar 2026",
    role: "Client",
    status: "Active",
    avatar: "https://i.pravatar.cc/40?img=9",
  },
  {
    id: 10,
    name: "Doris Crowley",
    email: "doris@example.com",
    date: "20 Mar 2026",
    role: "Client",
    status: "Active",
    avatar: "https://i.pravatar.cc/40?img=10",
  },
  {
    id: 11,
    name: "Emma Johnson",
    email: "emma@example.com",
    date: "01 Apr 2026",
    role: "Employee",
    status: "Active",
    avatar: "https://i.pravatar.cc/40?img=11",
  },
  {
    id: 12,
    name: "Daniel Parker",
    email: "daniel@example.com",
    date: "08 Apr 2026",
    role: "Client",
    status: "Active",
    avatar: "https://i.pravatar.cc/40?img=12",
  },
  {
    id: 13,
    name: "Olivia Brown",
    email: "olivia@example.com",
    date: "15 Apr 2026",
    role: "Employee",
    status: "Inactive",
    avatar: "https://i.pravatar.cc/40?img=13",
  },
  {
    id: 14,
    name: "James Wilson",
    email: "james@example.com",
    date: "22 Apr 2026",
    role: "Employee",
    status: "Active",
    avatar: "https://i.pravatar.cc/40?img=14",
  },
  {
    id: 15,
    name: "Charlotte Davis",
    email: "charlotte@example.com",
    date: "30 Apr 2026",
    role: "Client",
    status: "Active",
    avatar: "https://i.pravatar.cc/40?img=15",
  },
  {
    id: 16,
    name: "William Moore",
    email: "william@example.com",
    date: "05 May 2026",
    role: "Employee",
    status: "Active",
    avatar: "https://i.pravatar.cc/40?img=16",
  },
  {
    id: 17,
    name: "Sophia Taylor",
    email: "sophia@example.com",
    date: "12 May 2026",
    role: "Client",
    status: "Inactive",
    avatar: "https://i.pravatar.cc/40?img=17",
  },
  {
    id: 18,
    name: "Benjamin Anderson",
    email: "benjamin@example.com",
    date: "18 May 2026",
    role: "Employee",
    status: "Active",
    avatar: "https://i.pravatar.cc/40?img=18",
  },
  {
    id: 19,
    name: "Amelia Thomas",
    email: "amelia@example.com",
    date: "25 May 2026",
    role: "Client",
    status: "Active",
    avatar: "https://i.pravatar.cc/40?img=19",
  },
  {
    id: 20,
    name: "Henry Jackson",
    email: "henry@example.com",
    date: "30 May 2026",
    role: "Employee",
    status: "Active",
    avatar: "https://i.pravatar.cc/40?img=20",
  },
  {
    id: 21,
    name: "Mia White",
    email: "mia@example.com",
    date: "03 Jun 2026",
    role: "Client",
    status: "Active",
    avatar: "https://i.pravatar.cc/40?img=21",
  },
  {
    id: 22,
    name: "Lucas Harris",
    email: "lucas@example.com",
    date: "08 Jun 2026",
    role: "Employee",
    status: "Inactive",
    avatar: "https://i.pravatar.cc/40?img=22",
  },
  {
    id: 23,
    name: "Evelyn Martin",
    email: "evelyn@example.com",
    date: "14 Jun 2026",
    role: "Client",
    status: "Active",
    avatar: "https://i.pravatar.cc/40?img=23",
  },
  {
    id: 24,
    name: "Alexander Lee",
    email: "alexander@example.com",
    date: "20 Jun 2026",
    role: "Employee",
    status: "Active",
    avatar: "https://i.pravatar.cc/40?img=24",
  },
  {
    id: 25,
    name: "Harper Walker",
    email: "harper@example.com",
    date: "28 Jun 2026",
    role: "Client",
    status: "Active",
    avatar: "https://i.pravatar.cc/40?img=25",
  },
  {
    id: 26,
    name: "Elijah Hall",
    email: "elijah@example.com",
    date: "04 Jul 2026",
    role: "Employee",
    status: "Active",
    avatar: "https://i.pravatar.cc/40?img=26",
  },
  {
    id: 27,
    name: "Abigail Allen",
    email: "abigail@example.com",
    date: "10 Jul 2026",
    role: "Client",
    status: "Inactive",
    avatar: "https://i.pravatar.cc/40?img=27",
  },
  {
    id: 28,
    name: "Matthew Young",
    email: "matthew@example.com",
    date: "18 Jul 2026",
    role: "Employee",
    status: "Active",
    avatar: "https://i.pravatar.cc/40?img=28",
  },
  {
    id: 29,
    name: "Ella King",
    email: "ella@example.com",
    date: "25 Jul 2026",
    role: "Client",
    status: "Active",
    avatar: "https://i.pravatar.cc/40?img=29",
  },
  {
    id: 30,
    name: "David Wright",
    email: "david@example.com",
    date: "31 Jul 2026",
    role: "Employee",
    status: "Active",
    avatar: "https://i.pravatar.cc/40?img=30",
  },
  {
    id: 31,
    name: "Scarlett Scott",
    email: "scarlett@example.com",
    date: "05 Aug 2026",
    role: "Client",
    status: "Active",
    avatar: "https://i.pravatar.cc/40?img=31",
  },
  {
    id: 32,
    name: "Joseph Green",
    email: "joseph@example.com",
    date: "12 Aug 2026",
    role: "Employee",
    status: "Inactive",
    avatar: "https://i.pravatar.cc/40?img=32",
  },
  {
    id: 33,
    name: "Grace Baker",
    email: "grace@example.com",
    date: "18 Aug 2026",
    role: "Client",
    status: "Active",
    avatar: "https://i.pravatar.cc/40?img=33",
  },
  {
    id: 34,
    name: "Samuel Adams",
    email: "samuel@example.com",
    date: "25 Aug 2026",
    role: "Employee",
    status: "Active",
    avatar: "https://i.pravatar.cc/40?img=34",
  },
  {
    id: 35,
    name: "Chloe Nelson",
    email: "chloe@example.com",
    date: "02 Sep 2026",
    role: "Client",
    status: "Active",
    avatar: "https://i.pravatar.cc/40?img=35",
  },
  {
    id: 36,
    name: "Andrew Carter",
    email: "andrew@example.com",
    date: "10 Sep 2026",
    role: "Employee",
    status: "Active",
    avatar: "https://i.pravatar.cc/40?img=36",
  },
  {
    id: 37,
    name: "Lily Mitchell",
    email: "lily@example.com",
    date: "18 Sep 2026",
    role: "Client",
    status: "Inactive",
    avatar: "https://i.pravatar.cc/40?img=37",
  },
  {
    id: 38,
    name: "Christopher Perez",
    email: "christopher@example.com",
    date: "24 Sep 2026",
    role: "Employee",
    status: "Active",
    avatar: "https://i.pravatar.cc/40?img=38",
  },
  {
    id: 39,
    name: "Aria Roberts",
    email: "aria@example.com",
    date: "05 Oct 2026",
    role: "Client",
    status: "Active",
    avatar: "https://i.pravatar.cc/40?img=39",
  },
  {
    id: 40,
    name: "Jack Turner",
    email: "jack@example.com",
    date: "15 Oct 2026",
    role: "Employee",
    status: "Active",
    avatar: "https://i.pravatar.cc/40?img=40",
  },
];

export default allUsers;
