// ── Leave Employee – Mock Data & Constants ─────────────────────
import { CalendarDays, CalendarCheck, CalendarX, Clock } from "lucide-react";

export const LEAVE_TYPES_EMPLOYEE = [
  "Medical Leave",
  "Casual Leave",
  "Annual Leave",
  "Emergency Leave",
  "Maternity Leave",
  "Paternity Leave",
];

export const LEAVE_TYPES = [
  "All Types",
  "Medical Leave",
  "Casual Leave",
  "Annual Leave",
  "Emergency Leave",
  "Maternity Leave",
  "Paternity Leave",
];

export const DAY_TYPES = ["Full Day", "First Half", "Second Half"];

export const SORT_OPTIONS = [
  "Last 7 Days",
  "Last 30 Days",
  "Last 3 Months",
  "This Year",
];

export const ROWS_OPTIONS = [5, 10, 25, 50];

// Leave balance per type (mock)
export const LEAVE_BALANCE = {
  "Medical Leave": 10,
  "Casual Leave": 8,
  "Annual Leave": 15,
  "Emergency Leave": 3,
  "Maternity Leave": 90,
  "Paternity Leave": 7,
};

// Employee's own leave history (mock)
export const MY_LEAVE_DATA = [
  {
    id: 1,
    name: "John Doe",
    role: "Developer",
    avatar: "JD",
    color: "bg-blue-500",
    leaveType: "Casual Leave",
    from: "01 Jul 2026",
    to: "03 Jul 2026",
    days: 3,
    dayType: "Full Day",
    status: "Approved",
    reason: "Family function.",
  },
  {
    id: 2,
    name: "Aman Sharma",
    role: "Frontend Dev",
    avatar: "AS",
    color: "bg-green-500",
    leaveType: "Medical Leave",
    from: "05 Jul 2026",
    to: "06 Jul 2026",
    days: 2,
    dayType: "Full Day",
    status: "Pending",
    reason: "Fever.",
  },
  {
    id: 3,
    name: "Priya Singh",
    role: "HR",
    avatar: "PS",
    color: "bg-purple-500",
    leaveType: "Annual Leave",
    from: "10 Jul 2026",
    to: "15 Jul 2026",
    days: 6,
    dayType: "Full Day",
    status: "Approved",
    reason: "Vacation.",
  },
  {
    id: 4,
    name: "Rohit Verma",
    role: "Backend Dev",
    avatar: "RV",
    color: "bg-red-500",
    leaveType: "Emergency Leave",
    from: "12 Jul 2026",
    to: "13 Jul 2026",
    days: 2,
    dayType: "Half Day",
    status: "Rejected",
    reason: "Personal work.",
  },
  {
    id: 5,
    name: "Aman Sharma",
    role: "Frontend Dev",
    avatar: "AS",
    color: "bg-green-500",
    leaveType: "Casual Leave",
    from: "15 Jul 2026",
    to: "17 Jul 2026",
    days: 3,
    dayType: "Full Day",
    status: "Approved",
    reason: "Family function.",
  },
  {
    id: 6,
    name: "Neha Gupta",
    role: "HR",
    avatar: "NG",
    color: "bg-purple-500",
    leaveType: "Medical Leave",
    from: "18 Jul 2026",
    to: "19 Jul 2026",
    days: 2,
    dayType: "Half Day",
    status: "Pending",
    reason: "Doctor visit.",
  },
  {
    id: 7,
    name: "Rahul Singh",
    role: "Manager",
    avatar: "RS",
    color: "bg-yellow-500",
    leaveType: "Annual Leave",
    from: "20 Jul 2026",
    to: "24 Jul 2026",
    days: 5,
    dayType: "Full Day",
    status: "Approved",
    reason: "Vacation.",
  },
  {
    id: 8,
    name: "Simran Kaur",
    role: "Developer",
    avatar: "SK",
    color: "bg-pink-500",
    leaveType: "Emergency Leave",
    from: "25 Jul 2026",
    to: "26 Jul 2026",
    days: 2,
    dayType: "Full Day",
    status: "Rejected",
    reason: "Personal work.",
  },
  {
    id: 9,
    name: "Ankit Kumar",
    role: "Backend Dev",
    avatar: "AK",
    color: "bg-blue-500",
    leaveType: "Casual Leave",
    from: "01 Aug 2026",
    to: "02 Aug 2026",
    days: 2,
    dayType: "Half Day",
    status: "Pending",
    reason: "Family event.",
  },
  {
    id: 10,
    name: "Priya Sharma",
    role: "Designer",
    avatar: "PS",
    color: "bg-red-500",
    leaveType: "Medical Leave",
    from: "03 Aug 2026",
    to: "05 Aug 2026",
    days: 3,
    dayType: "Full Day",
    status: "Approved",
    reason: "Not feeling well.",
  },

  // same pattern continue...
  {
    id: 11,
    name: "Karan Mehta",
    role: "Developer",
    avatar: "KM",
    color: "bg-green-500",
    leaveType: "Annual Leave",
    from: "06 Aug 2026",
    to: "08 Aug 2026",
    days: 3,
    dayType: "Full Day",
    status: "Approved",
    reason: "Trip.",
  },
  {
    id: 12,
    name: "Riya Jain",
    role: "HR",
    avatar: "RJ",
    color: "bg-purple-500",
    leaveType: "Casual Leave",
    from: "09 Aug 2026",
    to: "10 Aug 2026",
    days: 2,
    dayType: "Half Day",
    status: "Pending",
    reason: "Personal work.",
  },
  {
    id: 13,
    name: "Deepak Roy",
    role: "Manager",
    avatar: "DR",
    color: "bg-yellow-500",
    leaveType: "Medical Leave",
    from: "11 Aug 2026",
    to: "13 Aug 2026",
    days: 3,
    dayType: "Full Day",
    status: "Rejected",
    reason: "Health issue.",
  },
  {
    id: 14,
    name: "Vikas Yadav",
    role: "Developer",
    avatar: "VY",
    color: "bg-pink-500",
    leaveType: "Emergency Leave",
    from: "14 Aug 2026",
    to: "15 Aug 2026",
    days: 2,
    dayType: "Full Day",
    status: "Approved",
    reason: "Emergency.",
  },
  {
    id: 15,
    name: "Pooja Verma",
    role: "Frontend Dev",
    avatar: "PV",
    color: "bg-blue-500",
    leaveType: "Annual Leave",
    from: "16 Aug 2026",
    to: "20 Aug 2026",
    days: 5,
    dayType: "Full Day",
    status: "Pending",
    reason: "Vacation.",
  },
  {
    id: 16,
    name: "Mohit Singh",
    role: "Backend Dev",
    avatar: "MS",
    color: "bg-red-500",
    leaveType: "Casual Leave",
    from: "21 Aug 2026",
    to: "22 Aug 2026",
    days: 2,
    dayType: "Half Day",
    status: "Approved",
    reason: "Family work.",
  },
  {
    id: 17,
    name: "Sneha Das",
    role: "HR",
    avatar: "SD",
    color: "bg-green-500",
    leaveType: "Medical Leave",
    from: "23 Aug 2026",
    to: "25 Aug 2026",
    days: 3,
    dayType: "Full Day",
    status: "Rejected",
    reason: "Medical.",
  },
  {
    id: 18,
    name: "Arjun Nair",
    role: "Manager",
    avatar: "AN",
    color: "bg-purple-500",
    leaveType: "Emergency Leave",
    from: "26 Aug 2026",
    to: "27 Aug 2026",
    days: 2,
    dayType: "Full Day",
    status: "Pending",
    reason: "Urgent work.",
  },
  {
    id: 19,
    name: "Meera Joshi",
    role: "Developer",
    avatar: "MJ",
    color: "bg-yellow-500",
    leaveType: "Casual Leave",
    from: "28 Aug 2026",
    to: "29 Aug 2026",
    days: 2,
    dayType: "Half Day",
    status: "Approved",
    reason: "Function.",
  },
  {
    id: 20,
    name: "Rakesh Pal",
    role: "Designer",
    avatar: "RP",
    color: "bg-pink-500",
    leaveType: "Annual Leave",
    from: "30 Aug 2026",
    to: "02 Sep 2026",
    days: 4,
    dayType: "Full Day",
    status: "Approved",
    reason: "Travel.",
  },
  // ... continue till 20
];

export const STAT_CARDS_EMPLOYEE = [
  {
    label: "Total Leaves",
    value: "24",
    icon: CalendarDays,
    gradient: "from-blue-400 to-blue-600",
    iconBg: "bg-blue-300/40",
  },
  {
    label: "Leaves Taken",
    value: "8",
    icon: CalendarCheck,
    gradient: "from-green-400 to-green-600",
    iconBg: "bg-green-300/40",
  },
  {
    label: "Remaining Leaves",
    value: "16",
    icon: CalendarX,
    gradient: "from-yellow-400 to-yellow-600",
    iconBg: "bg-yellow-300/40",
  },
  {
    label: "Pending Requests",
    value: "2",
    icon: Clock,
    gradient: "from-pink-400 to-pink-600",
    iconBg: "bg-pink-300/40",
  },
];
